### ISSUE TITLE
assignment2 problem

### ISSUE THREAD

**Issue by dzwduan** [xuwd11/cs231n_hws#1]
in layers.py conv_backward_naive, you dont add extra pad to x before backward and dimension got wrong.

**Comment by xuwd11** [comment]
@dzwduan 
In conv_forward_naive, I set
x = np.pad(x, n_pad, 'constant')
cache = (x, w, b, conv_param)
And in my backward pass, I have
x, w, b, conv_param = cache
dx = np.zeros_like(x)
So the dimension of x and dx in my backward pass is same as that of padded x in my forward pass.

**Comment by dzwduan** [comment]
get it ,thanks
